services:
    web:
        build: .
        ports:
            - "8080:80"
        environment:
            APP_URL: http://localhost:8080/
            DB_HOST: db
            DB_NAME: 51l20_olive_system
            DB_USER: root
            DB_PASS: root
        volumes:
            - ./src:/var/www/html
            - ./php.ini:/usr/local/etc/php/conf.d/docker-php-custom.ini

    db:
        image: mysql:8.0
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: 51l20_olive_system
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
